### ISSUE TITLE
在 Havoc Repo 中找不到 Write Now

### ISSUE THREAD

**Issue by Naco** [OwnGoalStudio/WriteNow#1]
> 添加 [Havoc Repo](https://havoc.app/) 到 Sileo 并登录仓库，然后下载并安装妙写。请搜索 Write Now。

iPhone 13 Pro 15.4.1，已经使用 Dopamine 2.2.2 越狱，但在 Sileo 的 Havoc Repo 中无论如何都搜索不到 Write Now，W 部根本就没有此项内容，见截图。

![IMG_0060](https://github.com/user-attachments/assets/3d32278e-0c08-4f7c-9cbe-a64f2e1a9ab4)

**Comment by Lessica** [comment]
这张图放在这里以供后世敬仰（看左上角三个最大的字）。

**Comment by Naco** [comment]
> 这张图放在这里以供后世敬仰（看左上角三个最大的字）。

有没有可能是Sileo显示的问题？你看看最下面我点开的是哪个Tab，而且列表里显示的插件很明显都没有已安装的插件上会显示的绿色对勾标志。

或者你打开你的Sileo，在所有分类里这个位置显示的是什么？

**Comment by Lakr233** [comment]
![image](https://github.com/user-attachments/assets/d8074e08-1e12-439f-924d-6f1f9d774796)

哥们 找得到有鬼了 右下角搜索请安排一下

**Comment by Naco** [comment]
> ![image](https://private-user-images.githubusercontent.com/25259084/362549668-d8074e08-1e12-439f-924d-6f1f9d774796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTQ1MDQsIm5iZiI6MTcyNDkxNDIwNCwicGF0aCI6Ii8yNTI1OTA4NC8zNjI1NDk2NjgtZDgwNzRlMDgtMWUxMi00MzlmLTkyNGQtNmYxZjlkNzc0Nzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA2NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDgzNmQ5OTZlOTM5ODg3MWVmNTMyYTNkYjNmNmMxNzk0MTlmNTk4MzNkZTMwNjEyODMyMzYxOWFjNzMyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V3ufMGj0o0WQw1lnga2KD9-OuQactFb8bVlaRbJ384g)
> 
> 哥们 找得到有鬼了 右下角搜索请安排一下

哥们，我上面的回复就是在解释这个问题。

这里显示的“已安装”是一个错误的显示，实际列表中显示的就是所有分类中的应用，而并不是我已经安装的应用。

1、在Sileo中，要查看已安装的应用，应该是在“软件包”的Tab，而不是在我截图的这个“软件源”的Tab；
2、真的已安装的应用，图标上会叠加显示一个绿色的对勾。

![微信图片_20240829152954](https://github.com/user-attachments/assets/1dc3a65f-1307-4e61-b24a-8997e7c525fb)
![微信图片_20240829153000](https://github.com/user-attachments/assets/db342846-1fe2-4aba-931d-b3b1f346fb16)

**Comment by Lakr233** [comment]
那你得找 Sileo 的团队看一下了。不瞒你说我也被骗过。之前做 Saily 的时候就没有这么多毛病，不懂这帮人在干啥。Sileo 这么多年了还是这么难用。。。我看看晚点更新一下 Saily 吧，如果还能做出来的话。

**Comment by Naco** [comment]
就这么不经意的，它，出现了……

我不知道是作者做了调整还是我的Sileo抽风，但我的确没有做任何改动，就突然有了。

另外看截图，左上角就是显示“已安装”…… 

![微信图片_20240829154015](https://github.com/user-attachments/assets/ab04db40-49d6-4614-881d-ded35062ebab)
