### ISSUE TITLE
永远提示“无法与服务器建立安全的连接”

### ISSUE THREAD

**Issue by Zhou-Shilin** [OwnGoalStudio/WriteNow#2]
![750959BB-3032-400C-B2CE-C42BC10CEA92](https://github.com/user-attachments/assets/b76f19e7-1d0a-4155-bda4-f5f45d7e3e7f)
如图所示，无论使用内建节点还是自定义节点，都会出现这个报错。

### 故障排除

1. 非自定义节点的问题，使用ChatBox和SiriPlus都能够正常使用，且使用内建节点也会出现这样的错误；
2. 网络正常，开/关代理无效；
3. ~~使用stream抓包，奇怪的一点是使用自定义节点时，请求并不会发送到自定义节点，而是向IP`134.195.14.32`发送了一个`CONNECT HTTP/1.1 keep-alive`请求，该请求未获得服务器响应。通过nslookup.io反查，未查找到其原域名；~~ 再次抓包后发现根本没有发出任何请求；
4. 如果断网，也会显示“无法与服务器建立安全的连接”，而不是“互联网不可用”。

### 系统信息
```markdown
- OS: iPadOS 16.2 Developer Beta 2
- JB: Dopamine 2 (Not Roothide)
- INS: Sileo, Havoc
- Type: Tweak
- Region: Suzhou, China
- ISP: Telecom
```

**Comment by Lessica** [comment]
请更新到 Version 1.9 解决上述部分问题后再试。

**Comment by Zhou-Shilin** [comment]
使用自定义节点返回错误代码404，使用内建节点返回代码403
然而可以正常获取模型列表
![4F29D251-5E49-4B76-A18F-B5DBDF24148C](https://github.com/user-attachments/assets/45a7b2f2-ca68-40fd-a2f5-37bb887e7f10)

**Comment by Zhou-Shilin** [comment]
@Lessica 可能需要reopen一下，我这边没有权限

**Comment by Lessica** [comment]
内建节点不支持在中国大陆地区使用。自定义节点需自行排查问题。

**Comment by Zhou-Shilin** [comment]
> 内建节点不支持在中国大陆地区使用。自定义节点需自行排查问题。

内建节点开启全局代理可以了
自定义节点 为何能够获得模型列表？在ChatBox或者其他应用中都可以正常使用

**Comment by Lessica** [comment]
自建节点要自己抓包排查下问题的，如果是因为我们客户端的请求不规范，可以反馈给我们。我们也有自建节点，没有类似问题。

**Comment by Lakr233** [comment]
看起来需要简单阐述一下妙写的工作逻辑：

- 插件会把 OpenAI 兼容的请求发往 http://127.0.0.1:5540
- 妙写服务会代理这个请求到上游节点

这个过程要求你的节点使用标准的 openai 请求 并且特殊说明这么做的原因：

- 模型和密钥信息会在代理时注入并修改
  - 此信息对妙写插件不可见 插件会成为宿主软件的一部分 访问沙盒外的信息存在安全隐患
  - 此信息对妙写服务可见 可以安全代理请求

基于上述逻辑 妙写使用了 MacPaw/OpenAI 作为底层框架处理请求 不支持配置 path

- 因此你的 /v1 配置会被忽略

插件自身会发送包含 /v1 的 path 目前已针对 GitHub Models 特殊处理删除了 /v1 的前缀

- 但是对于你的后台 我们没有文档也不知道要怎么处理

建议你排查来自 AIGate daemon 的请求 抓包解密 看一下是发到哪个 path 上面去了 我们可以给你单独适配一下

**Comment by Lakr233** [comment]
特别的：如果你挂了全局，在配置错误的情况下前往 127.0.0.1 的流量可能会被代理到远端。这不是代理软件设置错误，因为有用户这么需要这么用，但是显然妙写会在这个配置下停止工作。我们不负责处理这类问题。

**Comment by Lakr233** [comment]
关于获取模型列表的问题（假设上面的回复解答了你对 404/403 的疑惑）：

我们只能认定你的上游没有正确实现 OpenAI 定义的请求接口。此请求会从设置直接发出。在开发过程中我们已经发现 cloudflare 和类似的提供商不支持标准的响应结构，或者提供了不一致的响应数据。我们的处理逻辑会在最坏的情况下从数组中匹配名为 id model_id name 等字段的数据，但是无法确保你的响应能被正确解析。也需要单独适配了。

**Comment by Zhou-Shilin** [comment]
使用的是[OneAPI](https://github.com/songquanpeng/one-api)，应该是标准格式的。晚上抓包看看。
