### ISSUE TITLE
申请适配第三方API提供商【Siliconflow】（v1后缀）

### ISSUE THREAD

**Issue by Johnnybyzhang** [OwnGoalStudio/WriteNow#3]
目前使用的Lite版本，在内置编辑器中测试，永远是400报错，未能抓到有效的数据包，猜测可能和 #2 中一个情况，使用的服务的API文档地址为[https://docs.siliconflow.cn/docs](https://docs.siliconflow.cn/docs/4-api%E8%B0%83%E7%94%A8) ，需要针对/v1后缀单独适配。

**Comment by Lakr233** [comment]
检查了一下 你把填写 url 时候的 v1 删掉就能用了 不需要适配

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-09-11 at 15 20 02](https://github.com/user-attachments/assets/f51cd9f9-698a-4fc4-85ce-d0fd04e25411)
